# Define ports (1-4 or A, B or C), device types and node/topic names
/nxt_ros_setup:
  ros__parameters:
    1:
      sensor_type: touch
      sensor_name: touch_sensor
    3:
      sensor_type: reflected_light
      sensor_name: reflected_light_sensor
    4:
      sensor_type: ultrasonic
      sensor_name: ultrasonic_sensor
    A:
      motor_type: other
      motor_name: radar_motor
      motor_mimic_name: radar
      motor_mimic_gear_ratio: -0.33333
    B:
      motor_type: wheel_motor_l
      motor_name: wheel_motor_l
      motor_mimic_name: wheel_l
      motor_mimic_gear_ratio: -0.33333
    C:
      motor_type: wheel_motor_r
      motor_name: wheel_motor_r
      motor_mimic_name: wheel_r
      motor_mimic_gear_ratio: -0.33333
      # motor_mimic_gear_ratio > 0 -> mimic gear turns the same direction as the motor
      # motor_mimic_gear_ratio < 0 -> mimic gear turns in the opposite direction as the motor

# Define node specific/local parameters (has to match with name above)
/ultrasonic_sensor:
  ros__parameters:
    # Default values for LEGO Mindstorms NXT 2.0 ultrasonic sensor
    field_of_view: 0.5235988 # 30 degrees
    max_range: 2.54 # meters
    min_range: 0.07 # meters

/reflected_light_sensor:
  ros__parameters:
    rgb_color:
      - 0.0
      - 0.0
      - 0.0
